main/decks/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length


class CreateDeckForm(FlaskForm):
    title = StringField(validators=[DataRequired()])
    submit = SubmitField('Create')


class CreateCardForm(FlaskForm):
    front = StringField(validators=[DataRequired(), Length(
        max=500, message="Max 500 characters.")])
    back = TextAreaField(validators=[DataRequired(), Length(
        max=500, message="Max 500 characters.")])
    submit = SubmitField('Create Card')

main/cards/routes.py
from flask import Blueprint
from main import db
from flask import render_template, url_for, redirect, flash, abort
from main.cards.forms import EditCardForm
from main.models import Deck, Card
from flask_login import current_user, login_required

cards = Blueprint('cards', __name__)


@cards.route('/edit_card/<int:deck_id>/<int:card_id>', methods=['GET', 'POST'])
@login_required
def edit_card(deck_id, card_id):
    # Check if decks exists
    deck = Deck.query.get_or_404(deck_id)

    # If user doesn't own deck abort
    if deck.owner_id != current_user.id:
        abort(403)

    curr_card = Card.query.get_or_404(card_id)

    # Check if card belongs to deck
    if curr_card.deck_id != deck_id:
        abort(403)
    form = EditCardForm()
    if form.validate_on_submit():
        curr_card.front = form.front.data
        curr_card.back = form.back.data
        db.session.commit()
        flash("Card Updated!", "success")
        return redirect(url_for('cards.edit_card', deck_id=deck_id, card_id=card_id))
    form.front.data = curr_card.front
    form.back.data = curr_card.back
    return render_template('edit.html', title="Edit Card", deck_id=deck_id, card=curr_card, form=form)


@cards.route('/delete_card/<int:deck_id>/<int:card_id>')
@login_required
def delete_card(deck_id, card_id):
    # Check if decks exists
    deck = Deck.query.get_or_404(deck_id)

    # If user doesn't own deck abort
    if deck.owner_id != current_user.id:
        abort(403)

    # If card not found or doesn't belong to deck throw 404
    card = Card.query.get_or_404(card_id)
    if card.deck_id != deck_id:
        abort(404)
    db.session.delete(card)
    db.session.commit()
    return redirect(url_for('decks.deck', deck_id=deck_id))

main/decks/routes.py
from flask import Blueprint
from main import db
from flask import render_template, url_for, redirect, abort
from main.decks.forms import CreateDeckForm, CreateCardForm
from main.models import User, Deck, Card
from flask_login import current_user, login_required
import random

decks = Blueprint('decks', __name__)


@decks.route('/decks', methods=['GET', 'POST'])
@login_required
def all_decks():
    form = CreateDeckForm()
    if form.validate_on_submit():
        deck = Deck(title=form.title.data, owner_id=current_user.id)
        db.session.add(deck)
        db.session.commit()
        return redirect(url_for('decks.all_decks'))
    return render_template('decks.html', title="Decks", form=form, Card=Card)


@decks.route('/deck/<int:deck_id>', methods=['GET', 'POST'])
@login_required
def deck(deck_id):
    deck = Deck.query.get_or_404(deck_id)
    # TODO: Deck should exist!

    # Shouldn't want users to access decks they dont own!
    if deck.owner_id != current_user.id:
        abort(403)
    form = CreateCardForm()
    if form.validate_on_submit():
        card = Card(front=form.front.data,
                    back=form.back.data, deck_id=deck_id)
        db.session.add(card)
        db.session.commit()
        return redirect(url_for('decks.deck', deck_id=deck_id))
    return render_template('deck.html', title="Deck", deck=deck, form=form)


@decks.route('/study/<int:deck_id>')
@login_required
def study_deck(deck_id):
    deck = Deck.query.get_or_404(deck_id)
    # Can't study from a deck you don't own
    if deck.owner_id != current_user.id:
        abort(403)
    # Get all cards associated with deck -- shuffle them
    cards = Card.query.filter_by(deck_id=deck_id).all()
    random.shuffle(cards)
    return render_template('study.html', cards=cards)


@decks.route('/delete_deck/<int:deck_id>')
@login_required
def delete_deck(deck_id):
    # Shouldn't be able to delete deck if don't own it!
    deck = Deck.query.get_or_404(deck_id)
    if deck.owner_id != current_user.id:
        abort(403)

    # Delete all associated cards
    for card in Card.query.filter_by(deck_id=deck_id):
        db.session.delete(card)
    db.session.delete(deck)
    db.session.commit()
    # redirect to decks page
    return redirect(url_for('decks.all_decks'))

main/users/routes.py
from flask import Blueprint
from main import bcrypt, db
from flask import render_template, url_for, redirect, flash
from main.users.forms import RegistrationForm, LoginForm
from main.models import User
from flask_login import current_user, login_user, logout_user, login_required

users = Blueprint('users', __name__)


@users.route('/', methods=['GET', 'POST'])
@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('decks.all_decks'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None or not bcrypt.check_password_hash(user.password, form.password.data):
            flash('Invalid credentials', 'danger')
            return redirect(url_for('users.login'))
        login_user(user)
        return redirect(url_for('decks.all_decks'))
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('users.login'))


@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        new_user = User(email=form.email.data, password=hashed_password)
        db.session.add(new_user)
        db.session.commit()
        flash('Account created! You may now login.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

main/templates/deck.html
{% extends "index.html" %}
{% block content %}
          <div class="row justify-content-center">
        <h3>{{deck.title}}</h3>
      </div>
      <div class="row">
        <div class="col-md-6 text-center mt-3">
          <h4 class="text-center mb-3">Add A Card</h4>
          <form novalidate method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
              {% if form.front.errors %}
                {{ form.front(class="form-control form-control-sm is-invalid", placeholder="Card Front") }}
                <div class="invalid-feedback">
                  {% for error in form.front.errors %}
                    <span>{{ error }}</span>
                  {% endfor %}
                </div>
              {% else %}
                {{ form.front(class="form-control form-control-sm", placeholder="Card Front") }}
              {% endif %}
            </div>
            <div class="form-group">
              {% if form.back.errors %}
                {{ form.back(rows="3", class="form-control form-control-sm is-invalid", placeholder="Card Back") }}
                <div class="invalid-feedback">
                  {% for error in form.back.errors %}
                    <span>{{ error }}</span>
                  {% endfor %}
                </div>
              {% else %}
                {{ form.back(rows="3", class="form-control form-control-sm", placeholder="Card Back") }}
              {% endif %}
            </div>
            {{ form.submit(class="btn btn-outline-primary btn-block")}}
          </form>
        </div>
        <div class="col-md-6 mt-3">
          {% for card in deck.cards %}
            <div class="row align-items-center justify-content-center">
                <p>
                    <a href="{{ url_for('cards.edit_card', deck_id=deck.id, card_id=card.id) }}">{{ card.front }}</a>
                    <a href="{{ url_for('cards.delete_card', deck_id=deck.id, card_id=card.id) }}"><i class="fas fa-trash ml-2" style="color: red;"></i></a>
                </p>
            </div>

          {% endfor %}
            {# <p>
              <a href="#">Word 1</a>
              <a href="#"><i class="fas fa-trash ml-2"></i></a>
            </p> #}
          <!-- <ul class="list-unstyled" style="border: 2px solid pink">
            <li
              class="d-flex justify-content-center"
              style="border: 2px solid yellow"
            >
              <p>Word 1</p>
              <i class="fas fa-trash"></i>
            </li>
            <li>word2</li>
          </ul> -->
        </div>
      </div>
{% endblock content %}

main/templates/decks.html
{% extends 'index.html' %}
{% block content %}
        <div class="row">
        <div class="col-1-sm col-md-3 text-center mt-3">
            <div class="card">
                <div class="card-header">
                    <h4>Add Deck</h4>
                </div>
                <div class="card-footer">
                    <!-- Modal Trigger -->
                    <i class="fas fa-plus-square fa-2x" style="cursor: pointer;" data-toggle="modal" data-target="#deckModal"></i>
                    
                    <!-- Add Deck Modal -->
                    <div class="modal" id="deckModal">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Create A New Deck</h5>
                                    <button class="close" data-dismiss="modal">&times;</button>
                                </div>
                                <div class="modal-body">
                                    <form novalidate method="POST" id="addForm">
                                        {{ form.hidden_tag() }}
                                        <div class="form-group">
                                            {% if form.title.errors %}
                                                {{ form.title(class="form-control is-invalid", placeholder="Deck Title") }}
                                                <div class="invalid-feedback">
                                                    {% for error in form.title.errors %}
                                                        <span>{{ error }} </span>
                                                    {% endfor %}
                                                </div>
                                            {% else %}
                                                {{ form.title(class="form-control", placeholder="Deck Title") }}
                                            {% endif %}
                                        </div>
                                        {# {{ form.submit(class="btn btn-success") }} #}
                                    </form>
                                </div>
                                <div class="modal-footer">
                                    {{ form.submit(class="btn btn-success", form="addForm") }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        {% for deck in current_user.decks %}
            <div class="col-1-sm col-md-3 text-center mt-3">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title"><a href="{{url_for('decks.deck', deck_id=deck.id)}}">{{ deck.title }}</a></h4>
                        <p class="card-text">Cards: {{ Card.query.filter_by(deck_id=deck.id).count() }}</p>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col">
                                <a href="{{ url_for('decks.study_deck', deck_id=deck.id) }}" style="color: green;"><i class="fas fa-book-reader fa-2x mb-1"></i></a>
                            </div>
                            <div class="col">
                                <a href="{{url_for('decks.delete_deck', deck_id=deck.id)}}" style="color: red;"><i class="fas fa-trash fa-2x"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
{% endblock content %}

{% block scripts %}
    {% if form.errors %}
        <script type="text/javascript">
            $(window).on('load', function(){
                $('#deckModal').modal('show')
            })
        </script>
    {% endif %}
{% endblock scripts %}

main/templates/edit.html
{% extends "index.html" %}
{% block content %}
        {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="row justify-content-center">
            <div class="alert alert-{{ category }} alert-dismissable">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message }}
            </div>
          </div>
        {% endfor %}
      {% endif %}
    {% endwith%}
        <div class="row justify-content-center">
          <div class="col-md-8">
            <div class="card card-form">
              <div class="card-body">
                <h3 class="text-center mb-3">Edit Card</h3>
                <form novalidate method="POST">
                  {{ form.hidden_tag() }}
                  <div class="form-group">
                    {% if form.front.errors %}
                        {{ form.front(class="form-control form-control-sm is-invalid", placeholder="Card Front") }}
                        <div class="invalid-feedback">
                            {% for error in form.front.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.front(class="form-control form-control-sm", placeholder="Card Front") }}
                    {% endif %}
                  </div>
                  <div class="form-group">
                     {% if form.back.errors %}
                        {{ form.back(class="form-control form-control-sm is-invalid", placeholder="Card Back") }}
                        <div class="invalid-feedback">
                            {% for error in form.back.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.back(class="form-control form-control-sm", placeholder="Card Back") }}
                    {% endif %}
                  </div>
                  {{ form.submit(class="btn btn-outline-primary btn-block") }}
                  <a href="{{ url_for('decks.deck', deck_id=deck_id) }}" class="btn btn-outline-danger btn-block">Go Back</a>
                  {# <input
                    type="text"
                    value="Go Back"
                    class="btn btn-outline-danger btn-block"
                  /> #}
                </form>
              </div>
            </div>
          </div>
        </div>
{% endblock content %}

main/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <!-- Font Awesome -->
  <script src="https://kit.fontawesome.com/c00fccce60.js" ; crossorigin="anonymous" ;></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous" />
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />
  {% if title %}
  <title>Flashcard App - {{ title }}</title>
  {% else %}
  <title>Flashcard App</title>
  {% endif %}
  <title>Flashcard App</title>
</head>

<body>
  <!-- NAVBAR -->
  <nav class="navbar navbar-expand-sm bg-light navbar-light">
    <div class="container">
      <a href="#" class="navbar-brand">Flashcard App</a>
      <!-- Toggle Button -->
      <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Collapsable Menu on Small Screens -->
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
          {% if current_user.is_anonymous %}
            <li class="nav-item">
              <a href="{{url_for('users.register')}}" class="nav-link">Register</a>
            </li>
            <li class="nav-item">
              <a href="{{url_for('users.login')}}" class="nav-link">Login</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a href="{{url_for('decks.all_decks')}}" class="nav-link">Decks</a>
            </li>
            <li class="nav-item">
              <a href="{{url_for('users.logout')}}" class="nav-link">Logout</a>
            </li>
          {% endif %}
          
        </ul>
      </div>
    </div>
  </nav>

  <section class="mt-5">
    <div class="container">
      {% block content %}
      {% endblock content%}
    </div>
  </section>

  
  <!-- Bootstrap Stuff -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"></script>

  {% block scripts %}
  {% endblock scripts %}
</body>

</html>

main/templates/login.html
{% extends 'index.html'%} 
{% block content %}

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="row justify-content-center">
            <div class="alert alert-{{ category }}">{{ message }}</div>
          </div>
        {% endfor %}
      {% endif %}
    {% endwith%}
    <div class="row justify-content-center">
      <div class="card card-form">
        <div class="card-body">
          <h3 class="text-primary text-center mb-3">Login</h3>
          <form novalidate method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
              {% if form.email.errors %}
                {{ form.email(class="form-control form-control-sm is-invalid", placeholder="Email")}}
                <div class="invalid-feedback">
                  {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                  {% endfor %}
                </div>
              {% else %}
                {{ form.email(class="form-control form-control-sm", placeholder="Email")}}
              {% endif %}
            </div>
            <div class="form-group">
              {% if form.password.errors %}
                {{ form.password(class="form-control form-control-sm is-invalid", placeholder="Password")}}
                <div class="invalid-feedback">
                  {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                  {% endfor %}
                </div>
              {% else %}
                {{ form.password(class="form-control form-control-sm", placeholder="Password")}}
              {% endif %}
            </div>
            {{form.submit(class="btn btn-outline-primary btn-block")}}
          </form>
        </div>
      </div>
    </div>
    <div class="row justify-content-center mt-2">
      <p>
        Don't have an account? Click
        <a href="{{url_for('users.register')}}">here</a> to register.
      </p>
    </div>
{% endblock content%}

main/templates/register.html
{% extends 'index.html' %} {% block content %}
    <div class="row justify-content-center">
      <div class="card card-form">
        <div class="card-body">
          <h3 class="text-primary text-center mb-3">Register Today</h3>
          <form action="" method="POST" novalidate>
            {{ form.hidden_tag() }}
            <div class="form-group">
              {% if form.email.errors %} 
                {{ form.email(class="form-control form-control-sm is-invalid", placeholder="Email")}}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
              {% else %} 
                {{ form.email(class="form-control form-control-sm", placeholder="Email")}} 
              {% endif %}
            </div>
            <div class="form-group">
              {% if form.password.errors %}
                {{ form.password(class="form-control form-control-sm is-invalid", placeholder="Password")}}
                <div class="invalid-feedback">
                  {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                  {% endfor %}
                </div>
              {% else %}
                {{ form.password(class="form-control form-control-sm", placeholder="Password")}}
                <small class="form-text text-muted"> At least 5 characters.</small>
              {% endif %}
            </div>
            <div class="form-group">
              {% if form.confirmPassword.errors %}
                {{ form.confirmPassword(class="form-control form-control-sm is-invalid", placeholder="Confirm Password")}}
                <div class="invalid-feedback">
                  {% for error in form.confirmPassword.errors %}
                    <span>{{ error }}</span>
                  {% endfor %}
                </div>
              {% else %}
                {{ form.confirmPassword(class="form-control form-control-sm", placeholder="Confirm Password")}}
              {% endif %}
            </div>
            {{ form.submit(class="btn btn-outline-primary btn-block")}}
          </form>
        </div>
      </div>
    </div>
    <div class="row justify-content-center mt-2">
      <p>
        Already have an account? Click
        <a href="{{url_for('users.login')}}">here</a> to login.
      </p>
    </div>
{% endblock content %}

main/templates/study.html
{% extends "index.html" %}

{% block content %}
    {% if not cards %}
        <h4 class="text-center">You have no cards to study! Why don't you add some?</h4>
    {% else %}
        <div id="slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                {# Active Card Here #}
                <div class="carousel-item active">
                    <div class="row justify-content-center">
                        <div class="col d-flex justify-content-center bg-primary">
                            <div class="card study">
                                <div class="content">
                                    <div class="face-front z-depth-2">
                                        <div class="card-body">
                                            <p>{{ cards[0].front }}</p>
                                        </div>
                                    </div>
                                    <div class="face-back z-depth-2">
                                        <div class="card-body">
                                            <p>{{ cards[0].back }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% for card in cards[1:] %}
                    <div class="carousel-item">
                        <div class="row justify-content-center">
                            <div class="col d-flex justify-content-center bg-primary">
                                <div class="card study">
                                    <div class="content">
                                        <div class="face-front z-depth-2">
                                            <div class="card-body">
                                                <p>{{ card.front }}</p>
                                            </div>
                                        </div>
                                        <div class="face-back z-depth-2">
                                            <div class="card-body">
                                                <p>{{ card.back }}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <a href="#slider" class="carousel-control-prev" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
            </a>
            <a href="#slider" class="carousel-control-next" data-slide="next">
            <span class="carousel-control-next-icon" style="color: black"></span>
            </a>
        </div>
    {% endif %}
{% endblock content %}